name: ActionStudy
on: push

jobs:
  study-job:
    # job任务名称
    name: 研究Github Action任务
    # 指定运行所需要的虚拟机环境
    runs-on: ubuntu-latest
    # 执行步骤
    steps:
    - name: 第一个步骤
      # 该步骤所需的环境变量
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      # 步骤的运行的命令或者 action
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.